# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core API and NodeJs Client App to Azure Web Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./API

    strategy:
      matrix:
        dotnet-version: [8.x]

    steps:
      # Checkout the repo
      - uses: actions/checkout@main

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # Run dotnet build and publish
      - name: Dotnet Build and Publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release --property:PublishDir='./myapp'

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_API_CREDENTIALS }}

      # Deploy to Azure Web service
      - name: Run Azure Web API deploy action using Azure Credentials
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_API_APP_NAME }}
          package: ./API/myapp

      - name: Logout from Azure
        run: |
          az logout

  build-and-deploy-client-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ClientApp

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Checkout the repo
      - uses: actions/checkout@main

      # Setup NodeJs SDK
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Run npm build
      - name: NPM Build
        run: |
          npm install
          npm run build --if-present
          cp "web.config" "dist/codezen-template/web.config"

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CLIENT_CREDENTIALS }}

      # Deploy to Azure Web service
      - name: Run Azure webapp deploy action using Azure Credentials
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_CLIENT_APP_NAME }}
          package: ./ClientApp/dist/codezen-template

      - name: Logout from Azure
        run: |
          az logout
